<?php

namespace McRangeslider;


use McRangeslider\SearchBundleDBAL\Condition\RangeConditionHandler;
use McRangeslider\SearchBundleDBAL\CriteriaRequestHandler;
use McRangeslider\SearchBundleDBAL\Facet\RangeFacetHandler;
use Shopware\Components\Plugin;
use Shopware\Components\Plugin\Context\InstallContext;
use Shopware\Components\Plugin\Context\ActivateContext;
use Shopware\Components\Plugin\Context\UninstallContext;

class McRangeslider extends Plugin{

    public function install(InstallContext $context)
    {
        parent::install($context); // TODO: Change the autogenerated stub
    }
    public function uninstall(UninstallContext $context)
    {
        parent::uninstall($context); // TODO: Change the autogenerated stub
    }
    public function activate(ActivateContext $context)
    {
        parent::activate($context); // TODO: Change the autogenerated stub
    }

    public static function getSubscribedEvents()
    {
        return [
            'Enlight_Controller_Front_DispatchLoopStartup' => 'onStartDispatch',
            'Shopware_SearchBundleDBAL_Collect_Facet_Handlers' => 'registerFacetHandlers',
            'Shopware_SearchBundleDBAL_Collect_Condition_Handlers' => 'registerConditionHandlers',
            'Shopware_SearchBundle_Collect_Criteria_Request_Handlers' => 'registerRequestHandlers'
        ];
    }

    public function onStartDispatch(\Enlight_Event_EventArgs $ea){
        $test = Shopware()->Container()->get('shopware_searchdbal.dbal_query_builder_factory');
        $this->registerMyComponents();
        //die(var_dump($test));
    }

    public function registerMyComponents()
    {
        require_once $this->getPath() . '/vendor/autoload.php';
    }

    public function registerFacetHandlers(){
        return new RangeFacetHandler(
            Shopware()->Container()->get('shopware_searchdbal.dbal_query_builder_factory')
        );
    }

    public function registerConditionHandlers(){
        return new  RangeConditionHandler();
    }

    public function registerRequestHandlers(){
        return new CriteriaRequestHandler(
            Shopware()->Container()->get('dbal_connection')
        );
    }
}